url : http://kenev.net
name : 押入れ工房
description : Oscillate Cobalt
paginate: 30
# Includes an icon in the footer for each user name you enter
footer-links :
  github : kenfdev
  twitter : kenfdev
  linkedin : kenfdev
  stackoverflow : users/1692509/kenfdev

gems :
    - jekyll-feed
    - jekyll-paginate
    - jekyll-seo-tag

google_analytics : 'UA-44430359-7'

disqus : 'kenev'
highlighter: rouge
